# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=20, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=5)),
                ('location', models.CharField(choices=[(b'ind', b'india'), (b'aus', b'AUS')], max_length=10)),
                ('marital_status', models.CharField(max_length=5)),
            ],
        ),
    ]
